version: '3'

services:
  db:
    image: postgres:13-alpine
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: health_data_local
      POSTGRES_USER: health_data_local
      POSTGRES_PASSWORD: ''
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - db-data-health-data:/var/lib/postgresql/data

volumes:
  db-data-health-data: