server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/health_data_local
    username: health_data_local
    password:
    hikari:
      maximum-pool-size: 40
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true